# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3dd0ed6a9bf5662dee25fe5bdf16383fe2ca334a5796dad1f40317a5f7ab1cea6ea5e54dc3108f763eee79a11025abdf931445f423b40bcca644b6eeec5ff425

test:
  secret_key_base: 0f4cf1efff15cfdf797d29ac236cbc8d97875974002f813c7ff68be34894c0f7bf9a984c8b95165144142be215bf0660b15a89d4e224993a4baa0c7a96810f32

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
